### ISSUE TITLE
segmentExplorer

### ISSUE THREAD

**Issue by MaoX17** [RichieMcMullen/laravel-strava#11]
**Is your feature request related to a problem? Please describe.**
Can you add this feature?

**Describe the solution you'd like**
 #
    # Strava Segments explore
    #
    public function exploreSegments($token, $bounds, $activity_type)
    {
        $url = $this->strava_uri . '/segments/explore?bounds='. $bounds .'&activity_type=' . $activity_type;
        $config = $this->bearer($token);
        $res = $this->get($url, $config);
        return $res;
    }

Thank you

**Comment by RichieMcMullen** [comment]
Feel free to create a pull request for this feature.

**Comment by MaoX17** [comment]
Sorry to late..
I've done :-)
