### ISSUE TITLE
The scope variable is not accepted during the authorization process

### ISSUE THREAD

**Issue by edwink75** [RichieMcMullen/laravel-strava#12]
**Describe the bug**
Trying to authorize my application, which works in a way, but I need a specific scope. The scope I sent to 

`    Strava::authenticate($scope='my needed scope here');`

does not work

**To Reproduce**
in the code the URL is hardcoded when it comes to the scope
Class Strava
line 37

`   #`
`        # Strava Authenticate`
`    #`
`   public function authenticate()`
`   {`
`     return redirect('https://www.strava.com/oauth/authorize?client_id='. $this->client_id .'&response_type=code&redirect_uri='. $this->redirect_uri . '&scope=read_all,profile:read_all,activity:read_all&state=strava');` 
`       }`

**Expected behavior**
I think it would be sufficient to have a parameter for the scope in the `ct_strava.php` file

**Comment by edwink75** [comment]
I can see that the problem has been fixed in this repository, but why isn't it fixed when I install it with composer?
Is there another package I need to install instead?
Documentation says : 
`composer require codetoad/strava`

**Comment by RichieMcMullen** [comment]
Try downloading this: composer require codetoad/strava 1.0.8

**Comment by edwink75** [comment]
it does install version 1.0.8 
`...# composer install`
`Loading composer repositories with package information`
`Installing dependencies (including require-dev) from lock file`
`Package operations: 17 installs, 0 updates, 0 removals`
`  - Installing codetoad/strava (v1.0.8): Downloading (100%)`

**Comment by jacovdbergh** [comment]
The commit that fixed this issue is on master, @RichieMcMullen can you maybe release 1.0.9 to include that?

Thanks!

**Comment by RichieMcMullen** [comment]
1.0.9 Released
