### ISSUE TITLE
Strava::activities($token, $perPage, $after, $before);

### ISSUE THREAD

**Issue by shane-sigma** [RichieMcMullen/laravel-strava#3]
**User Activities Data**
In the guidelines you have this...
`Strava::activities($token, $perPage, $after, $before);`

Unless I am missing something the function looks like this and is missing the parameters

```
public function activities($token, $perPage = 10)
    {
        $url = $this->strava_uri . '/athlete/activities?per_page=' . $perPage;
        $config = $this->bearer($token);
        $res = $this->get($url, $config);
        return $res;
    }
```

I re-worked mine to look like this, so I can fetch all activities by offsetting the page
```
public function activities($token, $perPage = 10, $page = 1)
    {
        $url = $this->strava_uri . '/athlete/activities?per_page=' . $perPage .  '&page=' . $page;
        $config = $this->bearer($token);
        $res = $this->get($url, $config);
        return $res;
    }
```

**Comment by RichieMcMullen** [comment]
@shane-sigma 

Thanks for that. I've updated the function. I've also reordered the parameters within the function, so adjust your method call as required.

Thanks for pointing that out.
