### ISSUE TITLE
Latest release doesn't include laravel 10 support

### ISSUE THREAD

**Issue by zkrige** [RichieMcMullen/laravel-strava#35]
the composer.json file from 1.0.12 only includes laravel 9 support.

please can you do a release with laravel 10 support

**Comment by zkrige** [comment]
@RichieMcMullen any chance this is doable?

**Comment by zkrige** [comment]
thank you @breadthe 

@RichieMcMullen I'm happy to take over maintenance of this repo if you no longer have time for it

**Comment by zkrige** [comment]
@breadthe I see this repo already includes laravel 10 support - the repo owner just needs to create a new release

**Comment by RichieMcMullen** [comment]
Support added and released

**Comment by RichieMcMullen** [comment]
Support added and released
