### ISSUE TITLE
Laravel 6.x compatible

### ISSUE THREAD

**Issue by RosiersRobin** [RichieMcMullen/laravel-strava#5]
Is it possible to have the package work for Laravel 6.x?

**Comment by RichieMcMullen** [comment]
Merged your pull request. Thanks

**Comment by SBrownAU** [comment]
This hasn't been updated on Packagist (https://packagist.org/packages/codetoad/strava#v1.0.2). As a result, there's no way to install along with Laravel 6.* currently?

**Comment by RichieMcMullen** [comment]
I've just updated packagist, please try now and confirm.

**Comment by SBrownAU** [comment]
Can updated versions (`1.0.3` and `1.0.4`), but still none with `illuminate/support` using a version 6.

**Comment by RichieMcMullen** [comment]
Ok. Try the latest version ```v1.0.8```

**Comment by SBrownAU** [comment]
> Ok. Try the latest version `v1.0.8`
> 
> `composer require codetoad/strava 1.0.8`

Thank you, that's done it.

**Comment by RichieMcMullen** [comment]
You're welcome. Enjoy!
