### ISSUE TITLE
Laravel 7 Compatibility

### ISSUE THREAD

**Issue by iDemonix** [RichieMcMullen/laravel-strava#7]
Currently installation fails on a fresh copy of Laravel 7.

I believe this is just a fix to dependencies in composer.json, but wanted to create a request to discuss which version strings to use now that Laravel is on a 6 monthly major release schedule. Currently some other packages are using ^8.0 for things like `laravel/support`

**Comment by RichieMcMullen** [comment]
I've merged your pull request. I'll check over this tomorrow to double check its working as expected.

**Comment by iDemonix** [comment]
Thanks, looking forward to trying out your library!

**Comment by RichieMcMullen** [comment]
Updated. Feel free to try it on your Laravel 7 package.
